# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/xenial64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 27017, guest_ip: "127.0.0.1", host: 57017, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  config.vm.provider "lxc" do |lxc, override|
    override.vm.box = "debian/stretch64"
    lxc.customize 'cgroup.memory.limit_in_bytes', '2048M'
    lxc.customize 'cgroup.cpuset.cpus', '0,1'
  end

  config.vm.provider "parallels" do |prl, override|
    override.vm.box = "parallels/ubuntu-16.04"
    prl.name = "python-restful-example-mongodb-vm"
    prl.memory = 2048
    prl.cpus = 2
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update

    # under ubuntu with Parallels, the grub update needs to know where to install
    # the boot code.  the following selects /dev/sda, which is also fine for lxc
    # providers and likely most others as well.  You may need to edit the settings
    # if you have boot problems with the VM after the updates are completed.
    debconf-set-selections /vagrant/grub-pc.conf

    apt-get -y upgrade
    apt-get -y autoremove
    apt-get install -y mongodb

    echo "Reconfiguring MongoDB..."
    MONGO_CONF=`tempfile`

    # NOTE: '\' must be escaped as '\\' in the following line so the sed command sees a single slash
    [[ -n "${MONGO_CONF}" ]] && sed 's/\\(bind_ip =\\).*/\\1 0.0.0.0/' < /etc/mongodb.conf > ${MONGO_CONF}
    [[ -n "${MONGO_CONF}" ]] && grep 'bind_ip.*' "${MONGO_CONF}"
    [[ -n "${MONGO_CONF}" ]] && mv ${MONGO_CONF} /etc/mongodb.conf
    [[ -w /etc/mongodb.conf ]] && chmod a+r /etc/mongodb.conf
    systemctl restart mongodb.service
    echo "done."
  SHELL
end
